### ISSUE TITLE
Deleting files on windows fails

### ISSUE THREAD

**Issue by b2m** [JKamlah/tesseractXplore#15]
Environment: Windows 10 with tesseractXplore **V0.2.2**

I have the following folder structure active:

- test
   - inventar
     - inventar-1.png
  - inventar.pdf
 
When trying to delete `inventar-1.png` via tesseractXplore the program somehow deletes the active folder `test` and crashes.

This is the corresponding log entry:

```log
[INFO   ] Base: Leaving application in progress...
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "tesseractXplore\app\app.py", line 414, in <module>
[WARNING] stderr:   File "tesseractXplore\app\app.py", line 410, in main
[WARNING] stderr:   File "kivy\app.py", line 950, in run
[WARNING] stderr:   File "kivy\base.py", line 582, in runTouchApp
[WARNING] stderr:   File "kivy\base.py", line 347, in mainloop
[WARNING] stderr:   File "kivy\base.py", line 391, in idle
[WARNING] stderr:   File "kivy\base.py", line 342, in dispatch_input
[WARNING] stderr:   File "kivy\base.py", line 308, in post_dispatch_input
[WARNING] stderr:   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
[WARNING] stderr:   File "kivymd\uix\behaviors\ripple_behavior.py", line 296, in on_touch_up
[WARNING] stderr:   File "kivymd\uix\button.py", line 981, in on_touch_up
[WARNING] stderr:   File "kivy\uix\behaviors\button.py", line 179, in on_touch_up
[WARNING] stderr:   File "kivy\_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
[WARNING] stderr:   File "kivy\_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
[WARNING] stderr:   File "kivy\_event.pyx", line 1172, in kivy._event.EventObservers._dispatch
[WARNING] stderr:   File "tesseractXplore\controllers\image_selection_controller.py", line 159, in delete_file_chooser_selection
[WARNING] stderr:   File "shutil.py", line 740, in rmtree
[WARNING] stderr:   File "shutil.py", line 599, in _rmtree_unsafe
[WARNING] stderr:   File "shutil.py", line 596, in _rmtree_unsafe
[WARNING] stderr: PermissionError: [WinError 5] Zugriff verweigert: 'C:\\Users\\BRosemann\\test\\inventar\\inventar-1.png'
```

Also note that we have no timestamps in the logfile 😞 .

**Comment by JKamlah** [comment]
Thanks for the description. The problem arose due the multiselection of files. It is solved and will be updated soon.
