### ISSUE TITLE
Problems with print on screen dialog

### ISSUE THREAD

**Issue by b2m** [JKamlah/tesseractXplore#17]
Environment: Windows 10 with tesseractXplore **V0.2.2**

 - The print on screen dialog somehow has no visible scrollbar.
 - When selecting multiple formats only one of them is shown.
 - It is not clear that saving results from the "print on screen" dialog they will end up in `stdout`.
 - Selecting PDF as format and using "print on screen" produces an error (see log below) that requires a restart of the application.
```
[WARNING] stderr: Exception in thread Thread-6:
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "threading.py", line 932, in _bootstrap_inner
[WARNING] stderr:   File "threading.py", line 870, in run
[WARNING] stderr:   File "tesseractXplore\controllers\tesseract_controller.py", line 140, in recognize
[WARNING] stderr:   File "tesseractXplore\recognizer.py", line 60, in recognize
[WARNING] stderr:     stdout = str(stdout.decode("utf-8"))
[WARNING] stderr: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 530: invalid start byte
```

**Comment by JKamlah** [comment]
The only visible scrollbar can atm be applied by a scrollview container and that seems to be buggy. So i implemented the necessary code and i will activate it, if there is a fix to this bug. The multiple formats are getting displayed but all in the one dialog window. Append a hint that it will be stored to `stdout` storage. The PDF problem is solved.
